AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
