version: '3.7'

services:
  api:
    build: .
    depends_on:
      - database
    links:
      - database
    ports:
      - $PORT:$PORT
    volumes:
      - .:/api:delegated

  database:
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_PASSWORD: $DATABASE_PASS
      POSTGRES_USER: $DATABASE_USER
    image: postgres:12.2-alpine
    ports:
      - $DATABASE_PORT
