version: '3.7'

services:
  api:
    build: .
    environment:
      DATABASE_URL: $DATABASE_URL
    volumes:
      - .:/api:delegated
    ports:
      - 5000:5000
    links:
      - database
    depends_on:
      - database

  database:
      image: postgres:12.2-alpine
      ports:
        - $DATABASE_PORT
      environment:
        POSTGRES_DB: $DATABASE_NAME
        POSTGRES_PASSWORD: $DATABASE_PASS
        POSTGRES_USER: $DATABASE_USER
