default: &default
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] %>
  encoding: utf-8
  host: <%= ENV['DATABASE_HOST'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER'] %>

development:
  <<: *default
  database: bowling-on-rails-development

production:
  <<: *default

test:
  <<: *default
  database: bowling-on-rails-test
